import { Injectable } from '@nestjs/common';
import { GmailMessage } from './gmail.types';

@Injectable()
export class GmailService {
  async fetchMessages(): Promise<GmailMessage[]> {
    await new Promise((r) => setTimeout(r, 300));

    return [
      {
        id: 'g1',
        subject: '【要対応】提案書の修正をお願いします',
        from: '鈴木部長 <suzuki@mycompany.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-24',
        body: '先日お願いしていた提案書ですが、第3章の数字を修正してください。明日までにお願いします。',
        isRead: true,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-04-25',
        senderType: 'internal',
      },
      {
        id: 'g2',
        subject: 'Re: サービス導入のご検討について',
        from: '渡辺 誠 <watanabe@abc-consulting.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-24',
        body: 'ご提案いただいた内容について、いくつかご質問があります。見積もりの詳細と導入スケジュールについてお教えいただけますでしょうか。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: false,
        project: 'ABCコンサルティング',
        senderType: 'client',
      },
      {
        id: 'g3',
        subject: '【緊急】本日の打ち合わせ資料について',
        from: '佐藤PM <sato@mycompany.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-26',
        body: '本日14時からのプロジェクトX進捗会議に向けて、資料を午前中に共有してください。よろしくお願いします。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-04-26',
        project: 'プロジェクトX',
        senderType: 'internal',
      },
      {
        id: 'g4',
        subject: '月次レポートの提出について',
        from: '管理本部 <kanri@mycompany.co.jp>',
        to: 'all@mycompany.co.jp',
        date: '2026-04-23',
        body: '今月の月次レポートを今月末（4月30日）までに提出してください。フォームはイントラネットからアクセスできます。',
        isRead: true,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-04-30',
        senderType: 'announcement',
      },
      {
        id: 'g5',
        subject: 'プロジェクトXのスケジュール確認',
        from: '山田 健 <yamada@def-corp.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-25',
        body: '先日のご提案、ありがとうございました。導入スケジュールについて今週中にご確認いただけますか？弊社内での決裁が必要なため、なるべく早くご連絡いただければ幸いです。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-05-02',
        project: 'DEF株式会社',
        senderType: 'client',
      },
      {
        id: 'g6',
        subject: '新機能リリースのお知らせ（社内ツール）',
        from: 'devteam@mycompany.co.jp',
        to: 'all@mycompany.co.jp',
        date: '2026-04-23',
        body: '社内ツールに新機能を追加しました。詳細はwikiをご参照ください。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: false,
        senderType: 'announcement',
      },
      {
        id: 'g7',
        subject: 'Re: 提案書レビューお願い',
        from: 'me@mycompany.co.jp',
        to: '中村さん <nakamura@mycompany.co.jp>',
        date: '2026-04-24',
        body: '了解です！提案書は今日中に送ります。少々お待ちください。',
        isRead: true,
        isReplied: true,
        direction: 'sent',
        hasDeadline: true,
        deadlineDate: '2026-04-24',
        senderType: 'internal',
      },
      {
        id: 'g8',
        subject: 'Re: 契約書の最終確認について',
        from: 'me@mycompany.co.jp',
        to: '法務部 <legal@mycompany.co.jp>',
        date: '2026-04-25',
        body: '承知しました。GHI商事との契約書については明日（4月26日）確認して折り返します。',
        isRead: true,
        isReplied: true,
        direction: 'sent',
        hasDeadline: true,
        deadlineDate: '2026-04-26',
        project: 'GHI商事',
        senderType: 'internal',
      },
      {
        id: 'g9',
        subject: 'Re: スプリントレビュー資料',
        from: 'me@mycompany.co.jp',
        to: 'チーム全体 <team@mycompany.co.jp>',
        date: '2026-04-24',
        body: 'スプリントレビュー資料は木曜（4月30日）までに仕上げます。',
        isRead: true,
        isReplied: true,
        direction: 'sent',
        hasDeadline: true,
        deadlineDate: '2026-04-30',
        senderType: 'internal',
      },
      {
        id: 'g10',
        subject: '【締切4/28】社員満足度アンケートへのご協力',
        from: '総務部 <somu@mycompany.co.jp>',
        to: 'all@mycompany.co.jp',
        date: '2026-04-24',
        body: '社員満足度アンケートを実施しています。4月28日までにご回答ください。所要時間は約10分です。',
        isRead: true,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-04-28',
        senderType: 'announcement',
      },
      {
        id: 'g11',
        subject: '来週のキックオフMTG議事録作成のお願い',
        from: '青木リーダー <aoki@mycompany.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-26',
        body: '来週月曜（5月4日）のキックオフMTG後に議事録を作成してもらえますか？テンプレートはTeamsにあります。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-05-04',
        senderType: 'internal',
      },
      {
        id: 'g12',
        subject: '請求書処理のご依頼',
        from: '経理部 <keiri@mycompany.co.jp>',
        to: 'me@mycompany.co.jp',
        date: '2026-04-23',
        body: '先月分の経費精算が未処理です。本日中に経費精算システムから申請をお願いします。',
        isRead: false,
        isReplied: false,
        direction: 'received',
        hasDeadline: true,
        deadlineDate: '2026-04-23',
        senderType: 'announcement',
      },
    ];
  }
}
